[{"name": "test.test_meeting_planes.MeetingPlanes.test_calls", "status": "passed", "message": "", "passed": true, "points": ["p03-07.1"], "backtrace": []}, {"name": "test.test_meeting_planes.MeetingPlanes.test_first", "status": "failed", "message": "16.999999999999996 != 22.999999999999993 within 7 places : Solution 17.000000 does not satisfy the first equation of system (a1=1, b1=4, c1=5, a2=3, b2=2, c2=1, a3=2, b3=4, c3=1)!", "passed": false, "points": ["p03-07.1"], "backtrace": ["  File \"/usr/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/home/du_ds/Documents/Git/PythonDataAnalysisCourse/hy-data-analysis-with-python-summer-2019/part03-e07_meeting_planes/test/test_meeting_planes.py\", line 42, in test_first\n    self.assertAlmostEqual(z, a1*y + b1*x+c1, msg=\"Solution %f does not satisfy the first equation of system %s!\" % (z, system))\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 878, in assertAlmostEqual\n    raise self.failureException(msg)\n"]}, {"name": "test.test_meeting_planes.MeetingPlanes.test_inconsistent", "status": "passed", "message": "", "passed": true, "points": ["p03-07.1"], "backtrace": []}, {"name": "test.test_meeting_planes.MeetingPlanes.test_underdetermined", "status": "passed", "message": "", "passed": true, "points": ["p03-07.1"], "backtrace": []}]