[{"name": "test.test_cycling_weather_continues.CyclingWeatherContinues.test_calls", "status": "failed", "message": "False is not true : You did not call merge method or function!", "passed": false, "points": ["p05-13.1"], "backtrace": ["  File \"/usr/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/home/du_ds/Documents/Git/PythonDataAnalysisCourse/hy-data-analysis-with-python-summer-2019/part05-e13_cycling_weather_continues/test/test_cycling_weather_continues.py\", line 70, in test_calls\n    self.assertTrue(merge_method_called or merge_func_called, msg=\"You did not call merge method or function!\")\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 682, in assertTrue\n    raise self.failureException(msg)\n"]}, {"name": "test.test_cycling_weather_continues.CyclingWeatherContinues.test_output", "status": "passed", "message": "", "passed": true, "points": ["p05-13.1"], "backtrace": []}, {"name": "test.test_cycling_weather_continues.CyclingWeatherContinues.test_return_type", "status": "failed", "message": "-17.006943491613413 != -15.8 within 1 places : Incorrect regression coefficient for precipitation!", "passed": false, "points": ["p05-13.1"], "backtrace": ["  File \"/usr/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/home/du_ds/Documents/Git/PythonDataAnalysisCourse/hy-data-analysis-with-python-summer-2019/part05-e13_cycling_weather_continues/test/test_cycling_weather_continues.py\", line 32, in test_return_type\n    msg=\"Incorrect regression coefficient for precipitation!\")\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 878, in assertAlmostEqual\n    raise self.failureException(msg)\n"]}]