[{"name": "test.test_two_dice.TwoDice.test_content", "status": "failed", "message": "Regex didn't match: '\\\\((\\\\d),\\\\s*(\\\\d)\\\\)' not found in '' : The output  was not in the requested format!", "passed": false, "points": ["p01-05.1"], "backtrace": ["  File \"/usr/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/home/du_ds/Documents/Git/PythonDataAnalysisCourse/hy-data-analysis-with-python-summer-2019/part01-e05_two_dice/test/test_two_dice.py\", line 29, in test_content\n    self.assertRegex(line, pattern, msg=\"The output %s was not in the requested format!\" % line)\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 1299, in assertRegex\n    raise self.failureException(msg)\n"]}, {"name": "test.test_two_dice.TwoDice.test_lines", "status": "failed", "message": "1 != 4 : The output should contain exactly four lines!", "passed": false, "points": ["p01-05.1"], "backtrace": ["  File \"/usr/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/home/du_ds/Documents/Git/PythonDataAnalysisCourse/hy-data-analysis-with-python-summer-2019/part01-e05_two_dice/test/test_two_dice.py\", line 21, in test_lines\n    self.assertEqual(len(result), 4, msg=\"The output should contain exactly four lines!\")\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 829, in assertEqual\n    assertion_func(first, second, msg=msg)\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 822, in _baseAssertEqual\n    raise self.failureException(msg)\n"]}]