[{"name": "test.test_missing_value_types.MissingValueTypes.test_columns", "status": "failed", "message": "src.missing_value_types.missing_value_types does not exist!", "passed": false, "points": ["p04-13.1"], "backtrace": ["  File \"/usr/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/home/du_ds/Documents/Git/PythonDataAnalysisCourse/hy-data-analysis-with-python-summer-2019/part04-e13_missing_value_types/test/test_missing_value_types.py\", line 30, in test_columns\n    df = missing_value_types()\n", "  File \"/home/du_ds/Documents/Git/PythonDataAnalysisCourse/hy-data-analysis-with-python-summer-2019/part04-e13_missing_value_types/tmc/utils.py\", line 11, in fail\n    raise AssertionError(err)\n"]}, {"name": "test.test_missing_value_types.MissingValueTypes.test_dtypes", "status": "failed", "message": "src.missing_value_types.missing_value_types does not exist!", "passed": false, "points": ["p04-13.1"], "backtrace": ["  File \"/usr/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/home/du_ds/Documents/Git/PythonDataAnalysisCourse/hy-data-analysis-with-python-summer-2019/part04-e13_missing_value_types/test/test_missing_value_types.py\", line 35, in test_dtypes\n    df = missing_value_types()\n", "  File \"/home/du_ds/Documents/Git/PythonDataAnalysisCourse/hy-data-analysis-with-python-summer-2019/part04-e13_missing_value_types/tmc/utils.py\", line 11, in fail\n    raise AssertionError(err)\n"]}, {"name": "test.test_missing_value_types.MissingValueTypes.test_index", "status": "failed", "message": "src.missing_value_types.missing_value_types does not exist!", "passed": false, "points": ["p04-13.1"], "backtrace": ["  File \"/usr/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/home/du_ds/Documents/Git/PythonDataAnalysisCourse/hy-data-analysis-with-python-summer-2019/part04-e13_missing_value_types/test/test_missing_value_types.py\", line 25, in test_index\n    df = missing_value_types()\n", "  File \"/home/du_ds/Documents/Git/PythonDataAnalysisCourse/hy-data-analysis-with-python-summer-2019/part04-e13_missing_value_types/tmc/utils.py\", line 11, in fail\n    raise AssertionError(err)\n"]}, {"name": "test.test_missing_value_types.MissingValueTypes.test_nan", "status": "failed", "message": "src.missing_value_types.missing_value_types does not exist!", "passed": false, "points": ["p04-13.1"], "backtrace": ["  File \"/usr/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/home/du_ds/Documents/Git/PythonDataAnalysisCourse/hy-data-analysis-with-python-summer-2019/part04-e13_missing_value_types/test/test_missing_value_types.py\", line 40, in test_nan\n    df = missing_value_types()\n", "  File \"/home/du_ds/Documents/Git/PythonDataAnalysisCourse/hy-data-analysis-with-python-summer-2019/part04-e13_missing_value_types/tmc/utils.py\", line 11, in fail\n    raise AssertionError(err)\n"]}, {"name": "test.test_missing_value_types.MissingValueTypes.test_shape", "status": "failed", "message": "src.missing_value_types.missing_value_types does not exist!", "passed": false, "points": ["p04-13.1"], "backtrace": ["  File \"/usr/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/home/du_ds/Documents/Git/PythonDataAnalysisCourse/hy-data-analysis-with-python-summer-2019/part04-e13_missing_value_types/test/test_missing_value_types.py\", line 21, in test_shape\n    df = missing_value_types()\n", "  File \"/home/du_ds/Documents/Git/PythonDataAnalysisCourse/hy-data-analysis-with-python-summer-2019/part04-e13_missing_value_types/tmc/utils.py\", line 11, in fail\n    raise AssertionError(err)\n"]}]