[{"name": "test.test_detect_ranges.DetectRanges.test_first", "status": "failed", "message": "src.detect_ranges.detect_ranges does not exist!", "passed": false, "points": ["p01-10.1"], "backtrace": ["  File \"/usr/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/home/du_ds/Documents/Git/PythonDataAnalysisCourse/hy-data-analysis-with-python-summer-2019/part01-e10_detect_ranges/test/test_detect_ranges.py\", line 21, in test_first\n    result = detect_ranges(L)\n", "  File \"/home/du_ds/Documents/Git/PythonDataAnalysisCourse/hy-data-analysis-with-python-summer-2019/part01-e10_detect_ranges/tmc/utils.py\", line 11, in fail\n    raise AssertionError(err)\n"]}, {"name": "test.test_detect_ranges.DetectRanges.test_random", "status": "failed", "message": "src.detect_ranges.detect_ranges does not exist!", "passed": false, "points": ["p01-10.1"], "backtrace": ["  File \"/usr/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/home/du_ds/Documents/Git/PythonDataAnalysisCourse/hy-data-analysis-with-python-summer-2019/part01-e10_detect_ranges/test/test_detect_ranges.py\", line 31, in test_random\n    result = detect_ranges(L)\n", "  File \"/home/du_ds/Documents/Git/PythonDataAnalysisCourse/hy-data-analysis-with-python-summer-2019/part01-e10_detect_ranges/tmc/utils.py\", line 11, in fail\n    raise AssertionError(err)\n"]}]