[{"name": "test.test_extract_numbers.ExtractNumbers.test_calls", "status": "failed", "message": "0 != 4 : Expected 4 calls of 'float'!", "passed": false, "points": ["p02-10.1"], "backtrace": ["  File \"/usr/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/home/du_ds/Documents/Git/PythonDataAnalysisCourse/hy-data-analysis-with-python-summer-2019/part02-e10_extract_numbers/test/test_extract_numbers.py\", line 26, in test_calls\n    self.assertEqual(fl.call_count, 4, msg=\"Expected 4 calls of 'float'!\")\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 829, in assertEqual\n    assertion_func(first, second, msg=msg)\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 822, in _baseAssertEqual\n    raise self.failureException(msg)\n"]}, {"name": "test.test_extract_numbers.ExtractNumbers.test_first", "status": "failed", "message": "Lists differ: [] != [123, 1.2, 13.2, -1]\n\nSecond list contains 4 additional elements.\nFirst extra element 0:\n123\n\n- []\n+ [123, 1.2, 13.2, -1] : Incorrect result for string abd 123 1.2 test 13.2 -1!", "passed": false, "points": ["p02-10.1"], "backtrace": ["  File \"/usr/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/home/du_ds/Documents/Git/PythonDataAnalysisCourse/hy-data-analysis-with-python-summer-2019/part02-e10_extract_numbers/test/test_extract_numbers.py\", line 21, in test_first\n    self.assertEqual(L, [123, 1.2, 13.2, -1], msg=\"Incorrect result for string %s!\" % s)\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 829, in assertEqual\n    assertion_func(first, second, msg=msg)\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 1028, in assertListEqual\n    self.assertSequenceEqual(list1, list2, msg, seq_type=list)\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 1010, in assertSequenceEqual\n    self.fail(msg)\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 670, in fail\n    raise self.failureException(msg)\n"]}, {"name": "test.test_extract_numbers.ExtractNumbers.test_random", "status": "failed", "message": "Lists differ: [-77, 30, 17, -28, 6, 56, 42, -46, -13, 94[166 chars] -16] != []\n\nFirst list contains 50 additional elements.\nFirst extra element 0:\n-77\n\n+ []\n- [-77,\n-  30,\n-  17,\n-  -28,\n-  6,\n-  56,\n-  42,\n-  -46,\n-  -13,\n-  94,\n-  -75,\n-  32,\n-  67,\n-  59,\n-  16,\n-  89,\n-  31,\n-  -12,\n-  51,\n-  2,\n-  -21,\n-  27,\n-  -99,\n-  68,\n-  75,\n-  26,\n-  -73,\n-  -54,\n-  -80,\n-  91,\n-  94,\n-  10,\n-  49,\n-  28,\n-  -93,\n-  -52,\n-  97,\n-  15,\n-  0,\n-  -44,\n-  45,\n-  -44,\n-  7,\n-  96,\n-  36,\n-  -60,\n-  8,\n-  -85,\n-  81,\n-  -16] : Incorrect result for string -77 30 17 -28 6 56 42 -46 -13 94 -75 32 67 59 16 89 31 -12 51 2 -21 27 -99 68 75 26 -73 -54 -80 91 94 10 49 28 -93 -52 97 15 0 -44 45 -44 7 96 36 -60 8 -85 81 -16!", "passed": false, "points": ["p02-10.1"], "backtrace": ["  File \"/usr/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/home/du_ds/Documents/Git/PythonDataAnalysisCourse/hy-data-analysis-with-python-summer-2019/part02-e10_extract_numbers/test/test_extract_numbers.py\", line 32, in test_random\n    self.assertEqual(L, result, msg=\"Incorrect result for string %s!\" % s)\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 829, in assertEqual\n    assertion_func(first, second, msg=msg)\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 1028, in assertListEqual\n    self.assertSequenceEqual(list1, list2, msg, seq_type=list)\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 1010, in assertSequenceEqual\n    self.fail(msg)\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 670, in fail\n    raise self.failureException(msg)\n"]}]